---
description: Pipeline for ingesting APM application logs.
processors:
  - pipeline:
      name: process_ppid
  - pipeline:
      name: observer_version
  - pipeline:
      name: observer_ids
  - pipeline:
      name: remove_ecs_version
  - geoip:
      if: ctx.event?.category == 'device'
      field: client.ip
      target_field: client.geo
      ignore_missing: true
      database_file: GeoLite2-City.mmdb
      on_failure:
        - remove:
            field: client.ip
            ignore_failure: true
            ignore_missing: true
